In [6]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from tqdm.notebook import tqdm
from selenium import webdriver

In [7]:
url = 'https://search.naver.com/search.naver?where=nexearch&sm=top_hty&fbm=1&ie=utf8&query=%EB%82%A0%EC%94%A8'

In [8]:
driver = webdriver.Chrome()

In [9]:
driver.get(url)

In [10]:
soup = BeautifulSoup(driver.page_source, 'html.parser')

In [11]:
temp0 = float(soup.select('.temperature_text')[0].text.strip().split('도')[1].strip('°'))

try:
    rain0 = 0
except:
    rain0 = 0

sort0 = int(soup.select('.sort')[1].text.split()[1].strip('%'))

try:
    snow0 = 0
except:
    snow0 = 0

wind = soup.select('.sort')[2].text.strip().strip('m/s')

In [12]:
wind

'남서풍 1.8'

In [13]:
def convert_wind(wind):
    way = wind.split()[0]
    speed = float(wind.split()[1])
    if way == '북풍':
        converted_wind = [speed, 0, 0, 0, 0, 0, 0, 0,
                          0, 0, 0, 0, 0, 0, 0, 0]
    if way == '북북동풍':
        converted_wind = [0, speed, 0, 0, 0, 0, 0, 0,
                          0, 0, 0, 0, 0, 0, 0, 0]
    if way == '북동풍':
        converted_wind = [0, 0, speed, 0, 0, 0, 0, 0,
                          0, 0, 0, 0, 0, 0, 0, 0]
    if way == '동북동풍':
        converted_wind = [0, 0, 0, speed, 0, 0, 0, 0,
                          0, 0, 0, 0, 0, 0, 0, 0]
    if way == '동풍':
        converted_wind = [0, 0, 0, 0, speed, 0, 0, 0,
                          0, 0, 0, 0, 0, 0, 0, 0]
    if way == '동남동풍':
        converted_wind = [0, 0, 0, 0, 0, speed, 0, 0,
                          0, 0, 0, 0, 0, 0, 0, 0]
    if way == '남동풍':
        converted_wind = [0, 0, 0, 0, 0, 0, speed, 0,
                          0, 0, 0, 0, 0, 0, 0, 0]
    if way == '남남동':
        converted_wind = [0, 0, 0, 0, 0, 0, 0, speed,
                          0, 0, 0, 0, 0, 0, 0, 0]
    if way == '남풍':
        converted_wind = [0, 0, 0, 0, 0, 0, 0, 0,
                          speed, 0, 0, 0, 0, 0, 0, 0]
    if way == '남남서':
        converted_wind = [0, 0, 0, 0, 0, 0, 0, 0,
                          0, speed, 0, 0, 0, 0, 0, 0]
    if way == '남서풍':
        converted_wind = [0, 0, 0, 0, 0, 0, 0, 0,
                          0, 0, speed, 0, 0, 0, 0, 0]
    if way == '서남서풍':
        converted_wind = [0, 0, 0, 0, 0, 0, 0, 0,
                          0, 0, 0, speed, 0, 0, 0, 0]
    if way == '서풍':
        converted_wind = [0, 0, 0, 0, 0, 0, 0, 0,
                          0, 0, 0, 0, speed, 0, 0, 0]
    if way == '서북서풍':
        converted_wind = [0, 0, 0, 0, 0, 0, 0, 0,
                          0, 0, 0, 0, 0, speed, 0, 0]
    if way == '북서풍':
        converted_wind = [0, 0, 0, 0, 0, 0, 0, 0,
                          0, 0, 0, 0, 0, 0, speed, 0]
    if way == '북북서풍':
        converted_wind = [0, 0, 0, 0, 0, 0, 0, 0,
                          0, 0, 0, 0, 0, 0, 0, speed]
    return converted_wind

In [14]:
wind0 = convert_wind(wind)

In [15]:
for text in soup.select('.num'):
    print(text)

<span class="num">17<span class="celsius">°</span></span>
<span class="num">15<span class="celsius">°</span></span>
<span class="num">14<span class="celsius">°</span></span>
<span class="num">13<span class="celsius">°</span></span>
<span class="num">13<span class="celsius">°</span></span>
<span class="num">12<span class="celsius">°</span></span>
<span class="num">12<span class="celsius">°</span></span>
<span class="num">11<span class="celsius">°</span></span>
<span class="num">11<span class="celsius">°</span></span>
<span class="num">11<span class="celsius">°</span></span>
<span class="num">10<span class="celsius">°</span></span>
<span class="num">10<span class="celsius">°</span></span>
<span class="num">10<span class="celsius">°</span></span>
<span class="num">11<span class="celsius">°</span></span>
<span class="num">12<span class="celsius">°</span></span>
<span class="num">14<span class="celsius">°</span></span>
<span class="num">16<span class="celsius">°</span></span>
<span class="n

In [16]:
temps = [temp0]
rains = [rain0]
sorts = [sort0]
snows = [snow0]

In [17]:
for i in range(23):
    temps.append(int(soup.select('.num')[i].text.strip('°')))
    sorts.append(int(soup.select('.num')[i+118].text))

In [18]:
temps

[17.4,
 17,
 15,
 14,
 13,
 13,
 12,
 12,
 11,
 11,
 11,
 10,
 10,
 10,
 11,
 12,
 14,
 16,
 17,
 19,
 20,
 21,
 21,
 20]

In [19]:
sorts

[25,
 70,
 65,
 65,
 70,
 70,
 70,
 60,
 55,
 55,
 40,
 35,
 30,
 30,
 30,
 35,
 45,
 50,
 60,
 65,
 70,
 70,
 75,
 80]

In [20]:
int(soup.select('.data_inner')[0].text.strip())

0

In [21]:
for i in range(23):
    rains.append(int(soup.select('.data_inner')[i].text.strip()))

In [22]:
rains

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [23]:
for text in soup.select('.value'):
    print(text)

<em class="value">-</em>
<em class="value">-</em>
<em class="value">-</em>
<em class="value">-</em>
<em class="value">-</em>
<em class="value">-</em>
<em class="value">0%</em>
<em class="value">0%</em>
<em class="value">0%</em>
<em class="value">0%</em>
<em class="value">0%</em>
<em class="value">0%</em>
<em class="value">0%</em>
<em class="value">0%</em>
<em class="value">0%</em>
<em class="value">0%</em>
<em class="value">0%</em>
<em class="value">0%</em>
<em class="value">0%</em>
<em class="value">0%</em>
<em class="value">0%</em>
<em class="value">0%</em>
<em class="value">30%</em>
<em class="value">30%</em>
<em class="value">30%</em>
<em class="value">30%</em>
<em class="value">30%</em>
<em class="value">30%</em>
<em class="value">30%</em>
<em class="value">30%</em>
<em class="value">30%</em>
<em class="value">60%</em>
<em class="value">60%</em>
<em class="value">60%</em>
<em class="value">60%</em>
<em class="value">60%</em>
<em class="value">60%</em>
<em class="value">60%</em>
<e

In [24]:
soup.select('.value')[59].text

'남풍'

In [25]:
int(soup.select('.num')[59].text)

1

In [26]:
ways = []
speeds = []
for i in range(23):
    ways.append(soup.select('.value')[i+59].text)
    speeds.append(soup.select('.num')[i+59].text)

In [27]:
ways

['남풍',
 '남풍',
 '남풍',
 '남풍',
 '남풍',
 '남풍',
 '남풍',
 '남풍',
 '남풍',
 '남동풍',
 '남풍',
 '남풍',
 '남풍',
 '남풍',
 '남서풍',
 '남서풍',
 '남서풍',
 '남서풍',
 '남서풍',
 '남서풍',
 '남서풍',
 '남풍',
 '남풍']

In [28]:
speeds

['1',
 '1',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '1',
 '2',
 '2',
 '3',
 '3',
 '3',
 '4',
 '4',
 '5',
 '4',
 '4',
 '3',
 '3',
 '2']

In [29]:
winds = []
for i in range(23):
    winds.append(ways[i]+' '+speeds[i])

In [30]:
winds

['남풍 1',
 '남풍 1',
 '남풍 2',
 '남풍 2',
 '남풍 2',
 '남풍 2',
 '남풍 2',
 '남풍 2',
 '남풍 2',
 '남동풍 1',
 '남풍 2',
 '남풍 2',
 '남풍 3',
 '남풍 3',
 '남서풍 3',
 '남서풍 4',
 '남서풍 4',
 '남서풍 5',
 '남서풍 4',
 '남서풍 4',
 '남서풍 3',
 '남풍 3',
 '남풍 2']

In [31]:
converted_winds = [wind0]
for wnd in winds:
    converted_winds.append(convert_wind(wnd))

In [32]:
converted_winds

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.8, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1.0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1.0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 2.0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 2.0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 2.0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 2.0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 2.0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 2.0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 2.0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1.0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 2.0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 2.0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 3.0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 3.0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3.0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4.0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4.0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5.0, 0, 0, 0, 

In [33]:
import numpy as np

In [34]:
np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [35]:
sum_winds = np.zeros(16)
for cw in converted_winds:
    sum_winds += np.array(cw)

In [36]:
sum_winds

array([ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  1. ,  0. , 31. ,  0. , 28.8,
        0. ,  0. ,  0. ,  0. ,  0. ])

In [37]:
final_wind = sum_winds / 24

In [38]:
final_wind

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.04166667, 0.        , 1.29166667, 0.        ,
       1.2       , 0.        , 0.        , 0.        , 0.        ,
       0.        ])

In [39]:
url1 = 'https://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&query=%EB%AF%B8%EC%84%B8%EB%A8%BC%EC%A7%80&oquery=%EC%84%9C%EC%9A%B8+%EB%AF%B8%EC%84%B8%EB%A8%BC%EC%A7%80&tqi=iZoMrdprvmZssjy0nmZssssssIR-151605'
url2 = 'https://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&query=%EC%B4%88%EB%AF%B8%EC%84%B8%EB%A8%BC%EC%A7%80&oquery=%EB%AF%B8%EC%84%B8%EB%A8%BC%EC%A7%80&tqi=iZoMWlprvmZsskOPn38sssssshs-010266'
response1 = requests.get(url1)
response2 = requests.get(url2)
soup1 = BeautifulSoup(response1.text, 'html.parser')
soup2 = BeautifulSoup(response2.text, 'html.parser')

In [40]:
soup1

<!DOCTYPE html>
 <html lang="ko"><head> <meta charset="utf-8"/> <meta content="always" name="referrer"/> <meta content="telephone=no,address=no,email=no" name="format-detection"/> <meta content="width=device-width,initial-scale=1.0,maximum-scale=2.0" name="viewport"/> <meta content="미세먼지 : 네이버 통합검색" property="og:title"> <meta content="https://ssl.pstatic.net/sstatic/search/common/og_v3.png" property="og:image"/> <meta content="'미세먼지'의 네이버 통합검색 결과입니다." property="og:description"/> <meta content="'미세먼지'의 네이버 통합검색 결과입니다." lang="ko" name="description"/> <title>미세먼지 : 네이버 통합검색</title> <link href="https://ssl.pstatic.net/sstatic/search/favicon/favicon_191118_pc.ico" rel="shortcut icon"/> <link href="https://ssl.pstatic.net/sstatic/search/opensearch-description.https.xml" rel="search" title="Naver" type="application/opensearchdescription+xml"><link href="https://ssl.pstatic.net/sstatic/search/pc/css/search1_230427.css" rel="stylesheet" type="text/css"/> <link href="https://ssl.pstatic.net/ssta

In [41]:
soup2

<!DOCTYPE html>
 <html lang="ko"><head> <meta charset="utf-8"/> <meta content="always" name="referrer"/> <meta content="telephone=no,address=no,email=no" name="format-detection"/> <meta content="width=device-width,initial-scale=1.0,maximum-scale=2.0" name="viewport"/> <meta content="초미세먼지 : 네이버 통합검색" property="og:title"> <meta content="https://ssl.pstatic.net/sstatic/search/common/og_v3.png" property="og:image"/> <meta content="'초미세먼지'의 네이버 통합검색 결과입니다." property="og:description"/> <meta content="'초미세먼지'의 네이버 통합검색 결과입니다." lang="ko" name="description"/> <title>초미세먼지 : 네이버 통합검색</title> <link href="https://ssl.pstatic.net/sstatic/search/favicon/favicon_191118_pc.ico" rel="shortcut icon"/> <link href="https://ssl.pstatic.net/sstatic/search/opensearch-description.https.xml" rel="search" title="Naver" type="application/opensearchdescription+xml"><link href="https://ssl.pstatic.net/sstatic/search/pc/css/search1_230427.css" rel="stylesheet" type="text/css"/> <link href="https://ssl.pstatic.net/

In [42]:
PM10 = soup1.select('.tb_scroll')[0].select('td')[0].text
PM25 = soup2.select('.tb_scroll')[0].select('td')[0].text

In [43]:
PM10

'61'

In [44]:
PM25

'37'

In [46]:
temperature = sum(temps) / len(temps)
precipitation = sum(rains) / len(rains)
humidity = sum(sorts) / len(sorts)

In [47]:
test_set = [PM10, PM25, temperature, precipitation, humidity] + list(final_wind)

In [48]:
test_set

['61',
 '37',
 14.475,
 0.0,
 55.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.041666666666666664,
 0.0,
 1.2916666666666667,
 0.0,
 1.2,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0]